all: clean q1 q2 q3 q4 q5 q6 q7 q8 q9
q1:
	gcc -Wall q1.c -o q1
q2:
	gcc -Wall q2.c -o q2
q3:
	gcc -Wall q3.c -o q3
q4:
	gcc -Wall q4.c -o q4
q5:
	gcc -Wall q5.c -o q5
q6:
	gcc -Wall q6.c -o q6
q7:
	gcc -Wall q7.c -o q7
q8:
	gcc -Wall q8.c -o q8
q9:
	gcc -Wall q9.c -o q9
clean:
	-rm q1 q2 q3 q4 q5 q6 q7 q8 q9